# Generated by Django 4.2.4 on 2023-09-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='tozih',
            field=models.CharField(max_length=890, null=True),
        ),
    ]
