# Generated by Django 4.2.4 on 2023-09-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0003_doctor_tozih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='matn',
            field=models.CharField(max_length=500),
        ),
    ]
