# Generated by Django 4.2.4 on 2023-09-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0004_alter_contact_matn'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='img',
            field=models.ImageField(null=True, upload_to='aks'),
        ),
    ]
